---
title: "NACE classification using RAG"
format: html
---

## Introduction
Deep learning methods provide new opportunities in classification tasks. One opportunity is to utilize pretrained LLMs to summarize large bodies of unorganized text such as yearly accounts or website data in a systematic way, and provides new opportunities in classification. Given the intense publication rate of new, open and better LLMs, this is an exciting area to explore for classification tasks. Directly using LLMs in the classification process, or in a RAG setup allows for opportunities where there may be minimal training data, or in a changing environment where LLMs are updated faster than locally trained models. 

## NACE classification example in Norway
The Norwegian business register contains a well-covered popluation of legal business entity units. With the introduction of a new revision of NACE codes in 2025 (revision 2.1), interest in new automated classification methods has increased. The limited training data avaiable at the time of re-classification is a consdierable problem; addressed also in WP10 - cluster 5. New methods using pretrained LLMs are of interest to determine if they can aid in automating parts of the classification task for newly registrering companies, and for those with activities that have significantly changed. 

In this pipeline, we provide an example of classification using a RAG setup using Norwegian business register data.
